#ifndef __DEBUG_PRINT_H
#define __DEBUG_PRINT_H

#ifndef _WIN32_WINNT
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x9999
#endif

#include <windows.h>
#include <stdio.h>
#include <conio.h>
#include "scintilla.h"
typedef struct{
	int val;
	char *name;
}NAME;

NAME wm_names[]={
{WM_NULL,"WM_NULL"}, //0x0000
{WM_CREATE,"WM_CREATE"}, //0x0001
{WM_DESTROY,"WM_DESTROY"}, //0x0002
{WM_MOVE,"WM_MOVE"}, //0x0003
{WM_SIZE,"WM_SIZE"}, //0x0005
{WM_ACTIVATE,"WM_ACTIVATE"}, //0x0006
{WM_SETFOCUS,"WM_SETFOCUS"}, //0x0007
{WM_KILLFOCUS,"WM_KILLFOCUS"}, //0x0008
{WM_ENABLE,"WM_ENABLE"}, //0x000A
{WM_SETREDRAW,"WM_SETREDRAW"}, //0x000B
{WM_SETTEXT,"WM_SETTEXT"}, //0x000C
{WM_GETTEXT,"WM_GETTEXT"}, //0x000D
{WM_GETTEXTLENGTH,"WM_GETTEXTLENGTH"}, //0x000E
{WM_PAINT,"WM_PAINT"}, //0x000F
{WM_CLOSE,"WM_CLOSE"}, //0x0010
{WM_QUERYENDSESSION,"WM_QUERYENDSESSION"}, //0x0011
{WM_QUIT,"WM_QUIT"}, //0x0012
{WM_QUERYOPEN,"WM_QUERYOPEN"}, //0x0013
{WM_ERASEBKGND,"WM_ERASEBKGND"}, //0x0014
{WM_SYSCOLORCHANGE,"WM_SYSCOLORCHANGE"}, //0x0015
{WM_ENDSESSION,"WM_ENDSESSION"}, //0x0016
{WM_SHOWWINDOW,"WM_SHOWWINDOW"}, //0x0018
{WM_WININICHANGE,"WM_WININICHANGE"}, //0x001A
{WM_SETTINGCHANGE,"WM_SETTINGCHANGE"}, //WM_WININICHANGE
{WM_DEVMODECHANGE,"WM_DEVMODECHANGE"}, //0x001B
{WM_ACTIVATEAPP,"WM_ACTIVATEAPP"}, //0x001C
{WM_FONTCHANGE,"WM_FONTCHANGE"}, //0x001D
{WM_TIMECHANGE,"WM_TIMECHANGE"}, //0x001E
{WM_CANCELMODE,"WM_CANCELMODE"}, //0x001F
{WM_SETCURSOR,"WM_SETCURSOR"}, //0x0020
{WM_MOUSEACTIVATE,"WM_MOUSEACTIVATE"}, //0x0021
{WM_CHILDACTIVATE,"WM_CHILDACTIVATE"}, //0x0022
{WM_QUEUESYNC,"WM_QUEUESYNC"}, //0x0023
{WM_GETMINMAXINFO,"WM_GETMINMAXINFO"}, //0x0024
{WM_PAINTICON,"WM_PAINTICON"}, //0x0026
{WM_ICONERASEBKGND,"WM_ICONERASEBKGND"}, //0x0027
{WM_NEXTDLGCTL,"WM_NEXTDLGCTL"}, //0x0028
{WM_SPOOLERSTATUS,"WM_SPOOLERSTATUS"}, //0x002A
{WM_DRAWITEM,"WM_DRAWITEM"}, //0x002B
{WM_MEASUREITEM,"WM_MEASUREITEM"}, //0x002C
{WM_DELETEITEM,"WM_DELETEITEM"}, //0x002D
{WM_VKEYTOITEM,"WM_VKEYTOITEM"}, //0x002E
{WM_CHARTOITEM,"WM_CHARTOITEM"}, //0x002F
{WM_SETFONT,"WM_SETFONT"}, //0x0030
{WM_GETFONT,"WM_GETFONT"}, //0x0031
{WM_SETHOTKEY,"WM_SETHOTKEY"}, //0x0032
{WM_GETHOTKEY,"WM_GETHOTKEY"}, //0x0033
{WM_QUERYDRAGICON,"WM_QUERYDRAGICON"}, //0x0037
{WM_COMPAREITEM,"WM_COMPAREITEM"}, //0x0039
{WM_GETOBJECT,"WM_GETOBJECT"}, //0x003D
{WM_COMPACTING,"WM_COMPACTING"}, //0x0041
{WM_COMMNOTIFY,"WM_COMMNOTIFY"}, //0x0044
{WM_WINDOWPOSCHANGING,"WM_WINDOWPOSCHANGING"}, //0x0046
{WM_WINDOWPOSCHANGED,"WM_WINDOWPOSCHANGED"}, //0x0047
{WM_POWER,"WM_POWER"}, //0x0048
{WM_COPYDATA,"WM_COPYDATA"}, //0x004A
{WM_CANCELJOURNAL,"WM_CANCELJOURNAL"}, //0x004B
{WM_NOTIFY,"WM_NOTIFY"}, //0x004E
{WM_INPUTLANGCHANGEREQUEST,"WM_INPUTLANGCHANGEREQUEST"}, //0x0050
{WM_INPUTLANGCHANGE,"WM_INPUTLANGCHANGE"}, //0x0051
{WM_TCARD,"WM_TCARD"}, //0x0052
{WM_HELP,"WM_HELP"}, //0x0053
{WM_USERCHANGED,"WM_USERCHANGED"}, //0x0054
{WM_NOTIFYFORMAT,"WM_NOTIFYFORMAT"}, //0x0055
{WM_CONTEXTMENU,"WM_CONTEXTMENU"}, //0x007B
{WM_STYLECHANGING,"WM_STYLECHANGING"}, //0x007C
{WM_STYLECHANGED,"WM_STYLECHANGED"}, //0x007D
{WM_DISPLAYCHANGE,"WM_DISPLAYCHANGE"}, //0x007E
{WM_GETICON,"WM_GETICON"}, //0x007F
{WM_SETICON,"WM_SETICON"}, //0x0080
{WM_NCCREATE,"WM_NCCREATE"}, //0x0081
{WM_NCDESTROY,"WM_NCDESTROY"}, //0x0082
{WM_NCCALCSIZE,"WM_NCCALCSIZE"}, //0x0083
{WM_NCHITTEST,"WM_NCHITTEST"}, //0x0084
{WM_NCPAINT,"WM_NCPAINT"}, //0x0085
{WM_NCACTIVATE,"WM_NCACTIVATE"}, //0x0086
{WM_GETDLGCODE,"WM_GETDLGCODE"}, //0x0087
{WM_SYNCPAINT,"WM_SYNCPAINT"}, //0x0088
{WM_NCMOUSEMOVE,"WM_NCMOUSEMOVE"}, //0x00A0
{WM_NCLBUTTONDOWN,"WM_NCLBUTTONDOWN"}, //0x00A1
{WM_NCLBUTTONUP,"WM_NCLBUTTONUP"}, //0x00A2
{WM_NCLBUTTONDBLCLK,"WM_NCLBUTTONDBLCLK"}, //0x00A3
{WM_NCRBUTTONDOWN,"WM_NCRBUTTONDOWN"}, //0x00A4
{WM_NCRBUTTONUP,"WM_NCRBUTTONUP"}, //0x00A5
{WM_NCRBUTTONDBLCLK,"WM_NCRBUTTONDBLCLK"}, //0x00A6
{WM_NCMBUTTONDOWN,"WM_NCMBUTTONDOWN"}, //0x00A7
{WM_NCMBUTTONUP,"WM_NCMBUTTONUP"}, //0x00A8
{WM_NCMBUTTONDBLCLK,"WM_NCMBUTTONDBLCLK"}, //0x00A9
{WM_KEYFIRST,"WM_KEYFIRST"}, //0x0100
{WM_KEYDOWN,"WM_KEYDOWN"}, //0x0100
{WM_KEYUP,"WM_KEYUP"}, //0x0101
{WM_CHAR,"WM_CHAR"}, //0x0102
{WM_DEADCHAR,"WM_DEADCHAR"}, //0x0103
{WM_SYSKEYDOWN,"WM_SYSKEYDOWN"}, //0x0104
{WM_SYSKEYUP,"WM_SYSKEYUP"}, //0x0105
{WM_SYSCHAR,"WM_SYSCHAR"}, //0x0106
{WM_SYSDEADCHAR,"WM_SYSDEADCHAR"}, //0x0107
{WM_KEYLAST,"WM_KEYLAST"}, //0x0108
{WM_IME_STARTCOMPOSITION,"WM_IME_STARTCOMPOSITION"}, //0x010D
{WM_IME_ENDCOMPOSITION,"WM_IME_ENDCOMPOSITION"}, //0x010E
{WM_IME_COMPOSITION,"WM_IME_COMPOSITION"}, //0x010F
{WM_IME_KEYLAST,"WM_IME_KEYLAST"}, //0x010F
{WM_INITDIALOG,"WM_INITDIALOG"}, //0x0110
{WM_COMMAND,"WM_COMMAND"}, //0x0111
{WM_SYSCOMMAND,"WM_SYSCOMMAND"}, //0x0112
{WM_TIMER,"WM_TIMER"}, //0x0113
{WM_HSCROLL,"WM_HSCROLL"}, //0x0114
{WM_VSCROLL,"WM_VSCROLL"}, //0x0115
{WM_INITMENU,"WM_INITMENU"}, //0x0116
{WM_INITMENUPOPUP,"WM_INITMENUPOPUP"}, //0x0117
{WM_MENUSELECT,"WM_MENUSELECT"}, //0x011F
{WM_MENUCHAR,"WM_MENUCHAR"}, //0x0120
{WM_ENTERIDLE,"WM_ENTERIDLE"}, //0x0121
{WM_MENURBUTTONUP,"WM_MENURBUTTONUP"}, //0x0122
{WM_MENUDRAG,"WM_MENUDRAG"}, //0x0123
{WM_MENUGETOBJECT,"WM_MENUGETOBJECT"}, //0x0124
{WM_UNINITMENUPOPUP,"WM_UNINITMENUPOPUP"}, //0x0125
{WM_MENUCOMMAND,"WM_MENUCOMMAND"}, //0x0126
{WM_CTLCOLORMSGBOX,"WM_CTLCOLORMSGBOX"}, //0x0132
{WM_CTLCOLOREDIT,"WM_CTLCOLOREDIT"}, //0x0133
{WM_CTLCOLORLISTBOX,"WM_CTLCOLORLISTBOX"}, //0x0134
{WM_CTLCOLORBTN,"WM_CTLCOLORBTN"}, //0x0135
{WM_CTLCOLORDLG,"WM_CTLCOLORDLG"}, //0x0136
{WM_CTLCOLORSCROLLBAR,"WM_CTLCOLORSCROLLBAR"}, //0x0137
{WM_CTLCOLORSTATIC,"WM_CTLCOLORSTATIC"}, //0x0138
{WM_MOUSEFIRST,"WM_MOUSEFIRST"}, //0x0200
{WM_MOUSEMOVE,"WM_MOUSEMOVE"}, //0x0200
{WM_LBUTTONDOWN,"WM_LBUTTONDOWN"}, //0x0201
{WM_LBUTTONUP,"WM_LBUTTONUP"}, //0x0202
{WM_LBUTTONDBLCLK,"WM_LBUTTONDBLCLK"}, //0x0203
{WM_RBUTTONDOWN,"WM_RBUTTONDOWN"}, //0x0204
{WM_RBUTTONUP,"WM_RBUTTONUP"}, //0x0205
{WM_RBUTTONDBLCLK,"WM_RBUTTONDBLCLK"}, //0x0206
{WM_MBUTTONDOWN,"WM_MBUTTONDOWN"}, //0x0207
{WM_MBUTTONUP,"WM_MBUTTONUP"}, //0x0208
{WM_MBUTTONDBLCLK,"WM_MBUTTONDBLCLK"}, //0x0209
{WM_MOUSEWHEEL,"WM_MOUSEWHEEL"}, //0x020A
{WM_MOUSELAST,"WM_MOUSELAST"}, //0x020A
{WM_MOUSELAST,"WM_MOUSELAST"}, //0x0209
{WM_PARENTNOTIFY,"WM_PARENTNOTIFY"}, //0x0210
{WM_ENTERMENULOOP,"WM_ENTERMENULOOP"}, //0x0211
{WM_EXITMENULOOP,"WM_EXITMENULOOP"}, //0x0212
{WM_NEXTMENU,"WM_NEXTMENU"}, //0x0213
{WM_SIZING,"WM_SIZING"}, //0x0214
{WM_CAPTURECHANGED,"WM_CAPTURECHANGED"}, //0x0215
{WM_MOVING,"WM_MOVING"}, //0x0216
{WM_POWERBROADCAST,"WM_POWERBROADCAST"}, //0x0218
{WM_DEVICECHANGE,"WM_DEVICECHANGE"}, //0x0219
{WM_MDICREATE,"WM_MDICREATE"}, //0x0220
{WM_MDIDESTROY,"WM_MDIDESTROY"}, //0x0221
{WM_MDIACTIVATE,"WM_MDIACTIVATE"}, //0x0222
{WM_MDIRESTORE,"WM_MDIRESTORE"}, //0x0223
{WM_MDINEXT,"WM_MDINEXT"}, //0x0224
{WM_MDIMAXIMIZE,"WM_MDIMAXIMIZE"}, //0x0225
{WM_MDITILE,"WM_MDITILE"}, //0x0226
{WM_MDICASCADE,"WM_MDICASCADE"}, //0x0227
{WM_MDIICONARRANGE,"WM_MDIICONARRANGE"}, //0x0228
{WM_MDIGETACTIVE,"WM_MDIGETACTIVE"}, //0x0229
{WM_MDISETMENU,"WM_MDISETMENU"}, //0x0230
{WM_ENTERSIZEMOVE,"WM_ENTERSIZEMOVE"}, //0x0231
{WM_EXITSIZEMOVE,"WM_EXITSIZEMOVE"}, //0x0232
{WM_DROPFILES,"WM_DROPFILES"}, //0x0233
{WM_MDIREFRESHMENU,"WM_MDIREFRESHMENU"}, //0x0234
{WM_IME_SETCONTEXT,"WM_IME_SETCONTEXT"}, //0x0281
{WM_IME_NOTIFY,"WM_IME_NOTIFY"}, //0x0282
{WM_IME_CONTROL,"WM_IME_CONTROL"}, //0x0283
{WM_IME_COMPOSITIONFULL,"WM_IME_COMPOSITIONFULL"}, //0x0284
{WM_IME_SELECT,"WM_IME_SELECT"}, //0x0285
{WM_IME_CHAR,"WM_IME_CHAR"}, //0x0286
{WM_IME_REQUEST,"WM_IME_REQUEST"}, //0x0288
{WM_IME_KEYDOWN,"WM_IME_KEYDOWN"}, //0x0290
{WM_IME_KEYUP,"WM_IME_KEYUP"}, //0x0291
{WM_MOUSEHOVER,"WM_MOUSEHOVER"}, //0x02A1
{WM_MOUSELEAVE,"WM_MOUSELEAVE"}, //0x02A3
{WM_CUT,"WM_CUT"}, //0x0300
{WM_COPY,"WM_COPY"}, //0x0301
{WM_PASTE,"WM_PASTE"}, //0x0302
{WM_CLEAR,"WM_CLEAR"}, //0x0303
{WM_UNDO,"WM_UNDO"}, //0x0304
{WM_RENDERFORMAT,"WM_RENDERFORMAT"}, //0x0305
{WM_RENDERALLFORMATS,"WM_RENDERALLFORMATS"}, //0x0306
{WM_DESTROYCLIPBOARD,"WM_DESTROYCLIPBOARD"}, //0x0307
{WM_DRAWCLIPBOARD,"WM_DRAWCLIPBOARD"}, //0x0308
{WM_PAINTCLIPBOARD,"WM_PAINTCLIPBOARD"}, //0x0309
{WM_VSCROLLCLIPBOARD,"WM_VSCROLLCLIPBOARD"}, //0x030A
{WM_SIZECLIPBOARD,"WM_SIZECLIPBOARD"}, //0x030B
{WM_ASKCBFORMATNAME,"WM_ASKCBFORMATNAME"}, //0x030C
{WM_CHANGECBCHAIN,"WM_CHANGECBCHAIN"}, //0x030D
{WM_HSCROLLCLIPBOARD,"WM_HSCROLLCLIPBOARD"}, //0x030E
{WM_QUERYNEWPALETTE,"WM_QUERYNEWPALETTE"}, //0x030F
{WM_PALETTEISCHANGING,"WM_PALETTEISCHANGING"}, //0x0310
{WM_PALETTECHANGED,"WM_PALETTECHANGED"}, //0x0311
{WM_HOTKEY,"WM_HOTKEY"}, //0x0312
{WM_PRINT,"WM_PRINT"}, //0x0317
{WM_PRINTCLIENT,"WM_PRINTCLIENT"}, //0x0318
{WM_HANDHELDFIRST,"WM_HANDHELDFIRST"}, //0x0358
{WM_HANDHELDLAST,"WM_HANDHELDLAST"}, //0x035F
{WM_AFXFIRST,"WM_AFXFIRST"}, //0x0360
{WM_AFXLAST,"WM_AFXLAST"}, //0x037F
{WM_PENWINFIRST,"WM_PENWINFIRST"}, //0x0380
{WM_PENWINLAST,"WM_PENWINLAST"}, //0x038F
{WM_APP,"WM_APP"}, //0x8000
{WM_USER,"WM_USER"}, //0x0400
};

NAME sci_names[]={
{SCI_START,"SCI_START"}, //2000
{SCI_OPTIONAL_START,"SCI_OPTIONAL_START"}, //3000
{SCI_LEXER_START,"SCI_LEXER_START"}, //4000
{SCI_ADDTEXT,"SCI_ADDTEXT"}, //2001
{SCI_ADDSTYLEDTEXT,"SCI_ADDSTYLEDTEXT"}, //2002
{SCI_INSERTTEXT,"SCI_INSERTTEXT"}, //2003
{SCI_CLEARALL,"SCI_CLEARALL"}, //2004
{SCI_CLEARDOCUMENTSTYLE,"SCI_CLEARDOCUMENTSTYLE"}, //2005
{SCI_GETLENGTH,"SCI_GETLENGTH"}, //2006
{SCI_GETCHARAT,"SCI_GETCHARAT"}, //2007
{SCI_GETCURRENTPOS,"SCI_GETCURRENTPOS"}, //2008
{SCI_GETANCHOR,"SCI_GETANCHOR"}, //2009
{SCI_GETSTYLEAT,"SCI_GETSTYLEAT"}, //2010
{SCI_REDO,"SCI_REDO"}, //2011
{SCI_SETUNDOCOLLECTION,"SCI_SETUNDOCOLLECTION"}, //2012
{SCI_SELECTALL,"SCI_SELECTALL"}, //2013
{SCI_SETSAVEPOINT,"SCI_SETSAVEPOINT"}, //2014
{SCI_GETSTYLEDTEXT,"SCI_GETSTYLEDTEXT"}, //2015
{SCI_CANREDO,"SCI_CANREDO"}, //2016
{SCI_MARKERLINEFROMHANDLE,"SCI_MARKERLINEFROMHANDLE"}, //2017
{SCI_MARKERDELETEHANDLE,"SCI_MARKERDELETEHANDLE"}, //2018
{SCI_GETUNDOCOLLECTION,"SCI_GETUNDOCOLLECTION"}, //2019
{SCI_GETVIEWWS,"SCI_GETVIEWWS"}, //2020
{SCI_SETVIEWWS,"SCI_SETVIEWWS"}, //2021
{SCI_POSITIONFROMPOINT,"SCI_POSITIONFROMPOINT"}, //2022
{SCI_POSITIONFROMPOINTCLOSE,"SCI_POSITIONFROMPOINTCLOSE"}, //2023
{SCI_GOTOLINE,"SCI_GOTOLINE"}, //2024
{SCI_GOTOPOS,"SCI_GOTOPOS"}, //2025
{SCI_SETANCHOR,"SCI_SETANCHOR"}, //2026
{SCI_GETCURLINE,"SCI_GETCURLINE"}, //2027
{SCI_GETENDSTYLED,"SCI_GETENDSTYLED"}, //2028
{SCI_CONVERTEOLS,"SCI_CONVERTEOLS"}, //2029
{SCI_GETEOLMODE,"SCI_GETEOLMODE"}, //2030
{SCI_SETEOLMODE,"SCI_SETEOLMODE"}, //2031
{SCI_STARTSTYLING,"SCI_STARTSTYLING"}, //2032
{SCI_SETSTYLING,"SCI_SETSTYLING"}, //2033
{SCI_GETBUFFEREDDRAW,"SCI_GETBUFFEREDDRAW"}, //2034
{SCI_SETBUFFEREDDRAW,"SCI_SETBUFFEREDDRAW"}, //2035
{SCI_SETTABWIDTH,"SCI_SETTABWIDTH"}, //2036
{SCI_GETTABWIDTH,"SCI_GETTABWIDTH"}, //2121
{SCI_SETCODEPAGE,"SCI_SETCODEPAGE"}, //2037
{SCI_SETUSEPALETTE,"SCI_SETUSEPALETTE"}, //2039
{SCI_MARKERDEFINE,"SCI_MARKERDEFINE"}, //2040
{SCI_MARKERSETFORE,"SCI_MARKERSETFORE"}, //2041
{SCI_MARKERSETBACK,"SCI_MARKERSETBACK"}, //2042
{SCI_MARKERSETBACKSELECTED,"SCI_MARKERSETBACKSELECTED"}, //2292
{SCI_MARKERENABLEHIGHLIGHT,"SCI_MARKERENABLEHIGHLIGHT"}, //2293
{SCI_MARKERADD,"SCI_MARKERADD"}, //2043
{SCI_MARKERDELETE,"SCI_MARKERDELETE"}, //2044
{SCI_MARKERDELETEALL,"SCI_MARKERDELETEALL"}, //2045
{SCI_MARKERGET,"SCI_MARKERGET"}, //2046
{SCI_MARKERNEXT,"SCI_MARKERNEXT"}, //2047
{SCI_MARKERPREVIOUS,"SCI_MARKERPREVIOUS"}, //2048
{SCI_MARKERDEFINEPIXMAP,"SCI_MARKERDEFINEPIXMAP"}, //2049
{SCI_MARKERADDSET,"SCI_MARKERADDSET"}, //2466
{SCI_MARKERSETALPHA,"SCI_MARKERSETALPHA"}, //2476
{SCI_SETMARGINTYPEN,"SCI_SETMARGINTYPEN"}, //2240
{SCI_GETMARGINTYPEN,"SCI_GETMARGINTYPEN"}, //2241
{SCI_SETMARGINWIDTHN,"SCI_SETMARGINWIDTHN"}, //2242
{SCI_GETMARGINWIDTHN,"SCI_GETMARGINWIDTHN"}, //2243
{SCI_SETMARGINMASKN,"SCI_SETMARGINMASKN"}, //2244
{SCI_GETMARGINMASKN,"SCI_GETMARGINMASKN"}, //2245
{SCI_SETMARGINSENSITIVEN,"SCI_SETMARGINSENSITIVEN"}, //2246
{SCI_GETMARGINSENSITIVEN,"SCI_GETMARGINSENSITIVEN"}, //2247
{SCI_SETMARGINCURSORN,"SCI_SETMARGINCURSORN"}, //2248
{SCI_GETMARGINCURSORN,"SCI_GETMARGINCURSORN"}, //2249
{SCI_STYLECLEARALL,"SCI_STYLECLEARALL"}, //2050
{SCI_STYLESETFORE,"SCI_STYLESETFORE"}, //2051
{SCI_STYLESETBACK,"SCI_STYLESETBACK"}, //2052
{SCI_STYLESETBOLD,"SCI_STYLESETBOLD"}, //2053
{SCI_STYLESETITALIC,"SCI_STYLESETITALIC"}, //2054
{SCI_STYLESETSIZE,"SCI_STYLESETSIZE"}, //2055
{SCI_STYLESETFONT,"SCI_STYLESETFONT"}, //2056
{SCI_STYLESETEOLFILLED,"SCI_STYLESETEOLFILLED"}, //2057
{SCI_STYLERESETDEFAULT,"SCI_STYLERESETDEFAULT"}, //2058
{SCI_STYLESETUNDERLINE,"SCI_STYLESETUNDERLINE"}, //2059
{SCI_STYLEGETFORE,"SCI_STYLEGETFORE"}, //2481
{SCI_STYLEGETBACK,"SCI_STYLEGETBACK"}, //2482
{SCI_STYLEGETBOLD,"SCI_STYLEGETBOLD"}, //2483
{SCI_STYLEGETITALIC,"SCI_STYLEGETITALIC"}, //2484
{SCI_STYLEGETSIZE,"SCI_STYLEGETSIZE"}, //2485
{SCI_STYLEGETFONT,"SCI_STYLEGETFONT"}, //2486
{SCI_STYLEGETEOLFILLED,"SCI_STYLEGETEOLFILLED"}, //2487
{SCI_STYLEGETUNDERLINE,"SCI_STYLEGETUNDERLINE"}, //2488
{SCI_STYLEGETCASE,"SCI_STYLEGETCASE"}, //2489
{SCI_STYLEGETCHARACTERSET,"SCI_STYLEGETCHARACTERSET"}, //2490
{SCI_STYLEGETVISIBLE,"SCI_STYLEGETVISIBLE"}, //2491
{SCI_STYLEGETCHANGEABLE,"SCI_STYLEGETCHANGEABLE"}, //2492
{SCI_STYLEGETHOTSPOT,"SCI_STYLEGETHOTSPOT"}, //2493
{SCI_STYLESETCASE,"SCI_STYLESETCASE"}, //2060
{SCI_STYLESETCHARACTERSET,"SCI_STYLESETCHARACTERSET"}, //2066
{SCI_STYLESETHOTSPOT,"SCI_STYLESETHOTSPOT"}, //2409
{SCI_SETSELFORE,"SCI_SETSELFORE"}, //2067
{SCI_SETSELBACK,"SCI_SETSELBACK"}, //2068
{SCI_GETSELALPHA,"SCI_GETSELALPHA"}, //2477
{SCI_SETSELALPHA,"SCI_SETSELALPHA"}, //2478
{SCI_GETSELEOLFILLED,"SCI_GETSELEOLFILLED"}, //2479
{SCI_SETSELEOLFILLED,"SCI_SETSELEOLFILLED"}, //2480
{SCI_SETCARETFORE,"SCI_SETCARETFORE"}, //2069
{SCI_ASSIGNCMDKEY,"SCI_ASSIGNCMDKEY"}, //2070
{SCI_CLEARCMDKEY,"SCI_CLEARCMDKEY"}, //2071
{SCI_CLEARALLCMDKEYS,"SCI_CLEARALLCMDKEYS"}, //2072
{SCI_SETSTYLINGEX,"SCI_SETSTYLINGEX"}, //2073
{SCI_STYLESETVISIBLE,"SCI_STYLESETVISIBLE"}, //2074
{SCI_GETCARETPERIOD,"SCI_GETCARETPERIOD"}, //2075
{SCI_SETCARETPERIOD,"SCI_SETCARETPERIOD"}, //2076
{SCI_SETWORDCHARS,"SCI_SETWORDCHARS"}, //2077
{SCI_BEGINUNDOACTION,"SCI_BEGINUNDOACTION"}, //2078
{SCI_ENDUNDOACTION,"SCI_ENDUNDOACTION"}, //2079
{SCI_INDICSETSTYLE,"SCI_INDICSETSTYLE"}, //2080
{SCI_INDICGETSTYLE,"SCI_INDICGETSTYLE"}, //2081
{SCI_INDICSETFORE,"SCI_INDICSETFORE"}, //2082
{SCI_INDICGETFORE,"SCI_INDICGETFORE"}, //2083
{SCI_INDICSETUNDER,"SCI_INDICSETUNDER"}, //2510
{SCI_INDICGETUNDER,"SCI_INDICGETUNDER"}, //2511
{SCI_GETCARETLINEVISIBLEALWAYS,"SCI_GETCARETLINEVISIBLEALWAYS"}, //3095
{SCI_SETCARETLINEVISIBLEALWAYS,"SCI_SETCARETLINEVISIBLEALWAYS"}, //3096
{SCI_SETWHITESPACEFORE,"SCI_SETWHITESPACEFORE"}, //2084
{SCI_SETWHITESPACEBACK,"SCI_SETWHITESPACEBACK"}, //2085
{SCI_SETWHITESPACESIZE,"SCI_SETWHITESPACESIZE"}, //2086
{SCI_GETWHITESPACESIZE,"SCI_GETWHITESPACESIZE"}, //2087
{SCI_SETSTYLEBITS,"SCI_SETSTYLEBITS"}, //2090
{SCI_GETSTYLEBITS,"SCI_GETSTYLEBITS"}, //2091
{SCI_SETLINESTATE,"SCI_SETLINESTATE"}, //2092
{SCI_GETLINESTATE,"SCI_GETLINESTATE"}, //2093
{SCI_GETMAXLINESTATE,"SCI_GETMAXLINESTATE"}, //2094
{SCI_GETCARETLINEVISIBLE,"SCI_GETCARETLINEVISIBLE"}, //2095
{SCI_SETCARETLINEVISIBLE,"SCI_SETCARETLINEVISIBLE"}, //2096
{SCI_GETCARETLINEBACK,"SCI_GETCARETLINEBACK"}, //2097
{SCI_SETCARETLINEBACK,"SCI_SETCARETLINEBACK"}, //2098
{SCI_STYLESETCHANGEABLE,"SCI_STYLESETCHANGEABLE"}, //2099
{SCI_AUTOCSHOW,"SCI_AUTOCSHOW"}, //2100
{SCI_AUTOCCANCEL,"SCI_AUTOCCANCEL"}, //2101
{SCI_AUTOCACTIVE,"SCI_AUTOCACTIVE"}, //2102
{SCI_AUTOCPOSSTART,"SCI_AUTOCPOSSTART"}, //2103
{SCI_AUTOCCOMPLETE,"SCI_AUTOCCOMPLETE"}, //2104
{SCI_AUTOCSTOPS,"SCI_AUTOCSTOPS"}, //2105
{SCI_AUTOCSETSEPARATOR,"SCI_AUTOCSETSEPARATOR"}, //2106
{SCI_AUTOCGETSEPARATOR,"SCI_AUTOCGETSEPARATOR"}, //2107
{SCI_AUTOCSELECT,"SCI_AUTOCSELECT"}, //2108
{SCI_AUTOCSETCANCELATSTART,"SCI_AUTOCSETCANCELATSTART"}, //2110
{SCI_AUTOCGETCANCELATSTART,"SCI_AUTOCGETCANCELATSTART"}, //2111
{SCI_AUTOCSETFILLUPS,"SCI_AUTOCSETFILLUPS"}, //2112
{SCI_AUTOCSETCHOOSESINGLE,"SCI_AUTOCSETCHOOSESINGLE"}, //2113
{SCI_AUTOCGETCHOOSESINGLE,"SCI_AUTOCGETCHOOSESINGLE"}, //2114
{SCI_AUTOCSETIGNORECASE,"SCI_AUTOCSETIGNORECASE"}, //2115
{SCI_AUTOCGETIGNORECASE,"SCI_AUTOCGETIGNORECASE"}, //2116
{SCI_USERLISTSHOW,"SCI_USERLISTSHOW"}, //2117
{SCI_AUTOCSETAUTOHIDE,"SCI_AUTOCSETAUTOHIDE"}, //2118
{SCI_AUTOCGETAUTOHIDE,"SCI_AUTOCGETAUTOHIDE"}, //2119
{SCI_AUTOCSETDROPRESTOFWORD,"SCI_AUTOCSETDROPRESTOFWORD"}, //2270
{SCI_AUTOCGETDROPRESTOFWORD,"SCI_AUTOCGETDROPRESTOFWORD"}, //2271
{SCI_REGISTERIMAGE,"SCI_REGISTERIMAGE"}, //2405
{SCI_CLEARREGISTEREDIMAGES,"SCI_CLEARREGISTEREDIMAGES"}, //2408
{SCI_AUTOCGETTYPESEPARATOR,"SCI_AUTOCGETTYPESEPARATOR"}, //2285
{SCI_AUTOCSETTYPESEPARATOR,"SCI_AUTOCSETTYPESEPARATOR"}, //2286
{SCI_AUTOCSETMAXWIDTH,"SCI_AUTOCSETMAXWIDTH"}, //2208
{SCI_AUTOCGETMAXWIDTH,"SCI_AUTOCGETMAXWIDTH"}, //2209
{SCI_AUTOCSETMAXHEIGHT,"SCI_AUTOCSETMAXHEIGHT"}, //2210
{SCI_AUTOCGETMAXHEIGHT,"SCI_AUTOCGETMAXHEIGHT"}, //2211
{SCI_SETINDENT,"SCI_SETINDENT"}, //2122
{SCI_GETINDENT,"SCI_GETINDENT"}, //2123
{SCI_SETUSETABS,"SCI_SETUSETABS"}, //2124
{SCI_GETUSETABS,"SCI_GETUSETABS"}, //2125
{SCI_SETLINEINDENTATION,"SCI_SETLINEINDENTATION"}, //2126
{SCI_GETLINEINDENTATION,"SCI_GETLINEINDENTATION"}, //2127
{SCI_GETLINEINDENTPOSITION,"SCI_GETLINEINDENTPOSITION"}, //2128
{SCI_GETCOLUMN,"SCI_GETCOLUMN"}, //2129
{SCI_SETHSCROLLBAR,"SCI_SETHSCROLLBAR"}, //2130
{SCI_GETHSCROLLBAR,"SCI_GETHSCROLLBAR"}, //2131
{SCI_SETINDENTATIONGUIDES,"SCI_SETINDENTATIONGUIDES"}, //2132
{SCI_GETINDENTATIONGUIDES,"SCI_GETINDENTATIONGUIDES"}, //2133
{SCI_SETHIGHLIGHTGUIDE,"SCI_SETHIGHLIGHTGUIDE"}, //2134
{SCI_GETHIGHLIGHTGUIDE,"SCI_GETHIGHLIGHTGUIDE"}, //2135
{SCI_GETLINEENDPOSITION,"SCI_GETLINEENDPOSITION"}, //2136
{SCI_GETCODEPAGE,"SCI_GETCODEPAGE"}, //2137
{SCI_GETCARETFORE,"SCI_GETCARETFORE"}, //2138
{SCI_GETUSEPALETTE,"SCI_GETUSEPALETTE"}, //2139
{SCI_GETREADONLY,"SCI_GETREADONLY"}, //2140
{SCI_SETCURRENTPOS,"SCI_SETCURRENTPOS"}, //2141
{SCI_SETSELECTIONSTART,"SCI_SETSELECTIONSTART"}, //2142
{SCI_GETSELECTIONSTART,"SCI_GETSELECTIONSTART"}, //2143
{SCI_SETSELECTIONEND,"SCI_SETSELECTIONEND"}, //2144
{SCI_GETSELECTIONEND,"SCI_GETSELECTIONEND"}, //2145
{SCI_SETEMPTYSELECTION,"SCI_SETEMPTYSELECTION"}, //2556
{SCI_SETPRINTMAGNIFICATION,"SCI_SETPRINTMAGNIFICATION"}, //2146
{SCI_GETPRINTMAGNIFICATION,"SCI_GETPRINTMAGNIFICATION"}, //2147
{SCI_SETPRINTCOLOURMODE,"SCI_SETPRINTCOLOURMODE"}, //2148
{SCI_GETPRINTCOLOURMODE,"SCI_GETPRINTCOLOURMODE"}, //2149
{SCI_FINDTEXT,"SCI_FINDTEXT"}, //2150
{SCI_FORMATRANGE,"SCI_FORMATRANGE"}, //2151
{SCI_GETFIRSTVISIBLELINE,"SCI_GETFIRSTVISIBLELINE"}, //2152
{SCI_GETLINE,"SCI_GETLINE"}, //2153
{SCI_GETLINECOUNT,"SCI_GETLINECOUNT"}, //2154
{SCI_SETMARGINLEFT,"SCI_SETMARGINLEFT"}, //2155
{SCI_GETMARGINLEFT,"SCI_GETMARGINLEFT"}, //2156
{SCI_SETMARGINRIGHT,"SCI_SETMARGINRIGHT"}, //2157
{SCI_GETMARGINRIGHT,"SCI_GETMARGINRIGHT"}, //2158
{SCI_GETMODIFY,"SCI_GETMODIFY"}, //2159
{SCI_SETSEL,"SCI_SETSEL"}, //2160
{SCI_GETSELTEXT,"SCI_GETSELTEXT"}, //2161
{SCI_GETTEXTRANGE,"SCI_GETTEXTRANGE"}, //2162
{SCI_HIDESELECTION,"SCI_HIDESELECTION"}, //2163
{SCI_POINTXFROMPOSITION,"SCI_POINTXFROMPOSITION"}, //2164
{SCI_POINTYFROMPOSITION,"SCI_POINTYFROMPOSITION"}, //2165
{SCI_LINEFROMPOSITION,"SCI_LINEFROMPOSITION"}, //2166
{SCI_POSITIONFROMLINE,"SCI_POSITIONFROMLINE"}, //2167
{SCI_LINESCROLL,"SCI_LINESCROLL"}, //2168
{SCI_SCROLLCARET,"SCI_SCROLLCARET"}, //2169
{SCI_REPLACESEL,"SCI_REPLACESEL"}, //2170
{SCI_SETREADONLY,"SCI_SETREADONLY"}, //2171
{SCI_NULL,"SCI_NULL"}, //2172
{SCI_CANPASTE,"SCI_CANPASTE"}, //2173
{SCI_CANUNDO,"SCI_CANUNDO"}, //2174
{SCI_EMPTYUNDOBUFFER,"SCI_EMPTYUNDOBUFFER"}, //2175
{SCI_UNDO,"SCI_UNDO"}, //2176
{SCI_CUT,"SCI_CUT"}, //2177
{SCI_COPY,"SCI_COPY"}, //2178
{SCI_PASTE,"SCI_PASTE"}, //2179
{SCI_CLEAR,"SCI_CLEAR"}, //2180
{SCI_SETTEXT,"SCI_SETTEXT"}, //2181
{SCI_GETTEXT,"SCI_GETTEXT"}, //2182
{SCI_GETTEXTLENGTH,"SCI_GETTEXTLENGTH"}, //2183
{SCI_GETDIRECTFUNCTION,"SCI_GETDIRECTFUNCTION"}, //2184
{SCI_GETDIRECTPOINTER,"SCI_GETDIRECTPOINTER"}, //2185
{SCI_SETOVERTYPE,"SCI_SETOVERTYPE"}, //2186
{SCI_GETOVERTYPE,"SCI_GETOVERTYPE"}, //2187
{SCI_SETCARETWIDTH,"SCI_SETCARETWIDTH"}, //2188
{SCI_GETCARETWIDTH,"SCI_GETCARETWIDTH"}, //2189
{SCI_SETTARGETSTART,"SCI_SETTARGETSTART"}, //2190
{SCI_GETTARGETSTART,"SCI_GETTARGETSTART"}, //2191
{SCI_SETTARGETEND,"SCI_SETTARGETEND"}, //2192
{SCI_GETTARGETEND,"SCI_GETTARGETEND"}, //2193
{SCI_REPLACETARGET,"SCI_REPLACETARGET"}, //2194
{SCI_REPLACETARGETRE,"SCI_REPLACETARGETRE"}, //2195
{SCI_SEARCHINTARGET,"SCI_SEARCHINTARGET"}, //2197
{SCI_SETSEARCHFLAGS,"SCI_SETSEARCHFLAGS"}, //2198
{SCI_GETSEARCHFLAGS,"SCI_GETSEARCHFLAGS"}, //2199
{SCI_CALLTIPSHOW,"SCI_CALLTIPSHOW"}, //2200
{SCI_CALLTIPCANCEL,"SCI_CALLTIPCANCEL"}, //2201
{SCI_CALLTIPACTIVE,"SCI_CALLTIPACTIVE"}, //2202
{SCI_CALLTIPPOSSTART,"SCI_CALLTIPPOSSTART"}, //2203
{SCI_CALLTIPSETHLT,"SCI_CALLTIPSETHLT"}, //2204
{SCI_CALLTIPSETBACK,"SCI_CALLTIPSETBACK"}, //2205
{SCI_CALLTIPSETFORE,"SCI_CALLTIPSETFORE"}, //2206
{SCI_CALLTIPSETFOREHLT,"SCI_CALLTIPSETFOREHLT"}, //2207
{SCI_CALLTIPUSESTYLE,"SCI_CALLTIPUSESTYLE"}, //2212
{SCI_VISIBLEFROMDOCLINE,"SCI_VISIBLEFROMDOCLINE"}, //2220
{SCI_DOCLINEFROMVISIBLE,"SCI_DOCLINEFROMVISIBLE"}, //2221
{SCI_WRAPCOUNT,"SCI_WRAPCOUNT"}, //2235
{SCI_SETFOLDLEVEL,"SCI_SETFOLDLEVEL"}, //2222
{SCI_GETFOLDLEVEL,"SCI_GETFOLDLEVEL"}, //2223
{SCI_GETLASTCHILD,"SCI_GETLASTCHILD"}, //2224
{SCI_GETFOLDPARENT,"SCI_GETFOLDPARENT"}, //2225
{SCI_SHOWLINES,"SCI_SHOWLINES"}, //2226
{SCI_HIDELINES,"SCI_HIDELINES"}, //2227
{SCI_GETLINEVISIBLE,"SCI_GETLINEVISIBLE"}, //2228
{SCI_SETFOLDEXPANDED,"SCI_SETFOLDEXPANDED"}, //2229
{SCI_GETFOLDEXPANDED,"SCI_GETFOLDEXPANDED"}, //2230
{SCI_TOGGLEFOLD,"SCI_TOGGLEFOLD"}, //2231
{SCI_ENSUREVISIBLE,"SCI_ENSUREVISIBLE"}, //2232
{SCI_SETFOLDFLAGS,"SCI_SETFOLDFLAGS"}, //2233
{SCI_ENSUREVISIBLEENFORCEPOLICY,"SCI_ENSUREVISIBLEENFORCEPOLICY"}, //2234
{SCI_SETTABINDENTS,"SCI_SETTABINDENTS"}, //2260
{SCI_GETTABINDENTS,"SCI_GETTABINDENTS"}, //2261
{SCI_SETBACKSPACEUNINDENTS,"SCI_SETBACKSPACEUNINDENTS"}, //2262
{SCI_GETBACKSPACEUNINDENTS,"SCI_GETBACKSPACEUNINDENTS"}, //2263
{SCI_SETMOUSEDWELLTIME,"SCI_SETMOUSEDWELLTIME"}, //2264
{SCI_GETMOUSEDWELLTIME,"SCI_GETMOUSEDWELLTIME"}, //2265
{SCI_WORDSTARTPOSITION,"SCI_WORDSTARTPOSITION"}, //2266
{SCI_WORDENDPOSITION,"SCI_WORDENDPOSITION"}, //2267
{SCI_SETWRAPMODE,"SCI_SETWRAPMODE"}, //2268
{SCI_GETWRAPMODE,"SCI_GETWRAPMODE"}, //2269
{SCI_SETWRAPVISUALFLAGS,"SCI_SETWRAPVISUALFLAGS"}, //2460
{SCI_GETWRAPVISUALFLAGS,"SCI_GETWRAPVISUALFLAGS"}, //2461
{SCI_SETWRAPVISUALFLAGSLOCATION,"SCI_SETWRAPVISUALFLAGSLOCATION"}, //2462
{SCI_GETWRAPVISUALFLAGSLOCATION,"SCI_GETWRAPVISUALFLAGSLOCATION"}, //2463
{SCI_SETWRAPSTARTINDENT,"SCI_SETWRAPSTARTINDENT"}, //2464
{SCI_GETWRAPSTARTINDENT,"SCI_GETWRAPSTARTINDENT"}, //2465
{SCI_SETWRAPINDENTMODE,"SCI_SETWRAPINDENTMODE"}, //2472
{SCI_GETWRAPINDENTMODE,"SCI_GETWRAPINDENTMODE"}, //2473
{SCI_SETLAYOUTCACHE,"SCI_SETLAYOUTCACHE"}, //2272
{SCI_GETLAYOUTCACHE,"SCI_GETLAYOUTCACHE"}, //2273
{SCI_SETSCROLLWIDTH,"SCI_SETSCROLLWIDTH"}, //2274
{SCI_GETSCROLLWIDTH,"SCI_GETSCROLLWIDTH"}, //2275
{SCI_SETSCROLLWIDTHTRACKING,"SCI_SETSCROLLWIDTHTRACKING"}, //2516
{SCI_GETSCROLLWIDTHTRACKING,"SCI_GETSCROLLWIDTHTRACKING"}, //2517
{SCI_TEXTWIDTH,"SCI_TEXTWIDTH"}, //2276
{SCI_SETENDATLASTLINE,"SCI_SETENDATLASTLINE"}, //2277
{SCI_GETENDATLASTLINE,"SCI_GETENDATLASTLINE"}, //2278
{SCI_TEXTHEIGHT,"SCI_TEXTHEIGHT"}, //2279
{SCI_SETVSCROLLBAR,"SCI_SETVSCROLLBAR"}, //2280
{SCI_GETVSCROLLBAR,"SCI_GETVSCROLLBAR"}, //2281
{SCI_APPENDTEXT,"SCI_APPENDTEXT"}, //2282
{SCI_GETTWOPHASEDRAW,"SCI_GETTWOPHASEDRAW"}, //2283
{SCI_SETTWOPHASEDRAW,"SCI_SETTWOPHASEDRAW"}, //2284
{SCI_SETFONTQUALITY,"SCI_SETFONTQUALITY"}, //2611
{SCI_GETFONTQUALITY,"SCI_GETFONTQUALITY"}, //2612
{SCI_SETFIRSTVISIBLELINE,"SCI_SETFIRSTVISIBLELINE"}, //2613
{SCI_SETMULTIPASTE,"SCI_SETMULTIPASTE"}, //2614
{SCI_GETMULTIPASTE,"SCI_GETMULTIPASTE"}, //2615
{SCI_GETTAG,"SCI_GETTAG"}, //2616
{SCI_TARGETFROMSELECTION,"SCI_TARGETFROMSELECTION"}, //2287
{SCI_LINESJOIN,"SCI_LINESJOIN"}, //2288
{SCI_LINESSPLIT,"SCI_LINESSPLIT"}, //2289
{SCI_SETFOLDMARGINCOLOUR,"SCI_SETFOLDMARGINCOLOUR"}, //2290
{SCI_SETFOLDMARGINHICOLOUR,"SCI_SETFOLDMARGINHICOLOUR"}, //2291
{SCI_LINEDOWN,"SCI_LINEDOWN"}, //2300
{SCI_LINEDOWNEXTEND,"SCI_LINEDOWNEXTEND"}, //2301
{SCI_LINEUP,"SCI_LINEUP"}, //2302
{SCI_LINEUPEXTEND,"SCI_LINEUPEXTEND"}, //2303
{SCI_CHARLEFT,"SCI_CHARLEFT"}, //2304
{SCI_CHARLEFTEXTEND,"SCI_CHARLEFTEXTEND"}, //2305
{SCI_CHARRIGHT,"SCI_CHARRIGHT"}, //2306
{SCI_CHARRIGHTEXTEND,"SCI_CHARRIGHTEXTEND"}, //2307
{SCI_WORDLEFT,"SCI_WORDLEFT"}, //2308
{SCI_WORDLEFTEXTEND,"SCI_WORDLEFTEXTEND"}, //2309
{SCI_WORDRIGHT,"SCI_WORDRIGHT"}, //2310
{SCI_WORDRIGHTEXTEND,"SCI_WORDRIGHTEXTEND"}, //2311
{SCI_HOME,"SCI_HOME"}, //2312
{SCI_HOMEEXTEND,"SCI_HOMEEXTEND"}, //2313
{SCI_LINEEND,"SCI_LINEEND"}, //2314
{SCI_LINEENDEXTEND,"SCI_LINEENDEXTEND"}, //2315
{SCI_DOCUMENTSTART,"SCI_DOCUMENTSTART"}, //2316
{SCI_DOCUMENTSTARTEXTEND,"SCI_DOCUMENTSTARTEXTEND"}, //2317
{SCI_DOCUMENTEND,"SCI_DOCUMENTEND"}, //2318
{SCI_DOCUMENTENDEXTEND,"SCI_DOCUMENTENDEXTEND"}, //2319
{SCI_PAGEUP,"SCI_PAGEUP"}, //2320
{SCI_PAGEUPEXTEND,"SCI_PAGEUPEXTEND"}, //2321
{SCI_PAGEDOWN,"SCI_PAGEDOWN"}, //2322
{SCI_PAGEDOWNEXTEND,"SCI_PAGEDOWNEXTEND"}, //2323
{SCI_EDITTOGGLEOVERTYPE,"SCI_EDITTOGGLEOVERTYPE"}, //2324
{SCI_CANCEL,"SCI_CANCEL"}, //2325
{SCI_DELETEBACK,"SCI_DELETEBACK"}, //2326
{SCI_TAB,"SCI_TAB"}, //2327
{SCI_BACKTAB,"SCI_BACKTAB"}, //2328
{SCI_NEWLINE,"SCI_NEWLINE"}, //2329
{SCI_FORMFEED,"SCI_FORMFEED"}, //2330
{SCI_VCHOME,"SCI_VCHOME"}, //2331
{SCI_VCHOMEEXTEND,"SCI_VCHOMEEXTEND"}, //2332
{SCI_ZOOMIN,"SCI_ZOOMIN"}, //2333
{SCI_ZOOMOUT,"SCI_ZOOMOUT"}, //2334
{SCI_DELWORDLEFT,"SCI_DELWORDLEFT"}, //2335
{SCI_DELWORDRIGHT,"SCI_DELWORDRIGHT"}, //2336
{SCI_DELWORDRIGHTEND,"SCI_DELWORDRIGHTEND"}, //2518
{SCI_LINECUT,"SCI_LINECUT"}, //2337
{SCI_LINEDELETE,"SCI_LINEDELETE"}, //2338
{SCI_LINETRANSPOSE,"SCI_LINETRANSPOSE"}, //2339
{SCI_LINEDUPLICATE,"SCI_LINEDUPLICATE"}, //2404
{SCI_LOWERCASE,"SCI_LOWERCASE"}, //2340
{SCI_UPPERCASE,"SCI_UPPERCASE"}, //2341
{SCI_LINESCROLLDOWN,"SCI_LINESCROLLDOWN"}, //2342
{SCI_LINESCROLLUP,"SCI_LINESCROLLUP"}, //2343
{SCI_DELETEBACKNOTLINE,"SCI_DELETEBACKNOTLINE"}, //2344
{SCI_HOMEDISPLAY,"SCI_HOMEDISPLAY"}, //2345
{SCI_HOMEDISPLAYEXTEND,"SCI_HOMEDISPLAYEXTEND"}, //2346
{SCI_LINEENDDISPLAY,"SCI_LINEENDDISPLAY"}, //2347
{SCI_LINEENDDISPLAYEXTEND,"SCI_LINEENDDISPLAYEXTEND"}, //2348
{SCI_HOMEWRAP,"SCI_HOMEWRAP"}, //2349
{SCI_HOMEWRAPEXTEND,"SCI_HOMEWRAPEXTEND"}, //2450
{SCI_LINEENDWRAP,"SCI_LINEENDWRAP"}, //2451
{SCI_LINEENDWRAPEXTEND,"SCI_LINEENDWRAPEXTEND"}, //2452
{SCI_VCHOMEWRAP,"SCI_VCHOMEWRAP"}, //2453
{SCI_VCHOMEWRAPEXTEND,"SCI_VCHOMEWRAPEXTEND"}, //2454
{SCI_LINECOPY,"SCI_LINECOPY"}, //2455
{SCI_MOVECARETINSIDEVIEW,"SCI_MOVECARETINSIDEVIEW"}, //2401
{SCI_LINELENGTH,"SCI_LINELENGTH"}, //2350
{SCI_BRACEHIGHLIGHT,"SCI_BRACEHIGHLIGHT"}, //2351
{SCI_BRACEHIGHLIGHTINDICATOR,"SCI_BRACEHIGHLIGHTINDICATOR"}, //2498
{SCI_BRACEBADLIGHT,"SCI_BRACEBADLIGHT"}, //2352
{SCI_BRACEBADLIGHTINDICATOR,"SCI_BRACEBADLIGHTINDICATOR"}, //2499
{SCI_BRACEMATCH,"SCI_BRACEMATCH"}, //2353
{SCI_GETVIEWEOL,"SCI_GETVIEWEOL"}, //2355
{SCI_SETVIEWEOL,"SCI_SETVIEWEOL"}, //2356
{SCI_GETDOCPOINTER,"SCI_GETDOCPOINTER"}, //2357
{SCI_SETDOCPOINTER,"SCI_SETDOCPOINTER"}, //2358
{SCI_SETMODEVENTMASK,"SCI_SETMODEVENTMASK"}, //2359
{SCI_GETEDGECOLUMN,"SCI_GETEDGECOLUMN"}, //2360
{SCI_SETEDGECOLUMN,"SCI_SETEDGECOLUMN"}, //2361
{SCI_GETEDGEMODE,"SCI_GETEDGEMODE"}, //2362
{SCI_SETEDGEMODE,"SCI_SETEDGEMODE"}, //2363
{SCI_GETEDGECOLOUR,"SCI_GETEDGECOLOUR"}, //2364
{SCI_SETEDGECOLOUR,"SCI_SETEDGECOLOUR"}, //2365
{SCI_SEARCHANCHOR,"SCI_SEARCHANCHOR"}, //2366
{SCI_SEARCHNEXT,"SCI_SEARCHNEXT"}, //2367
{SCI_SEARCHPREV,"SCI_SEARCHPREV"}, //2368
{SCI_LINESONSCREEN,"SCI_LINESONSCREEN"}, //2370
{SCI_USEPOPUP,"SCI_USEPOPUP"}, //2371
{SCI_SELECTIONISRECTANGLE,"SCI_SELECTIONISRECTANGLE"}, //2372
{SCI_SETZOOM,"SCI_SETZOOM"}, //2373
{SCI_GETZOOM,"SCI_GETZOOM"}, //2374
{SCI_CREATEDOCUMENT,"SCI_CREATEDOCUMENT"}, //2375
{SCI_ADDREFDOCUMENT,"SCI_ADDREFDOCUMENT"}, //2376
{SCI_RELEASEDOCUMENT,"SCI_RELEASEDOCUMENT"}, //2377
{SCI_GETMODEVENTMASK,"SCI_GETMODEVENTMASK"}, //2378
{SCI_SETFOCUS,"SCI_SETFOCUS"}, //2380
{SCI_GETFOCUS,"SCI_GETFOCUS"}, //2381
{SCI_SETSTATUS,"SCI_SETSTATUS"}, //2382
{SCI_GETSTATUS,"SCI_GETSTATUS"}, //2383
{SCI_SETMOUSEDOWNCAPTURES,"SCI_SETMOUSEDOWNCAPTURES"}, //2384
{SCI_GETMOUSEDOWNCAPTURES,"SCI_GETMOUSEDOWNCAPTURES"}, //2385
{SCI_SETCURSOR,"SCI_SETCURSOR"}, //2386
{SCI_GETCURSOR,"SCI_GETCURSOR"}, //2387
{SCI_SETCONTROLCHARSYMBOL,"SCI_SETCONTROLCHARSYMBOL"}, //2388
{SCI_GETCONTROLCHARSYMBOL,"SCI_GETCONTROLCHARSYMBOL"}, //2389
{SCI_WORDPARTLEFT,"SCI_WORDPARTLEFT"}, //2390
{SCI_WORDPARTLEFTEXTEND,"SCI_WORDPARTLEFTEXTEND"}, //2391
{SCI_WORDPARTRIGHT,"SCI_WORDPARTRIGHT"}, //2392
{SCI_WORDPARTRIGHTEXTEND,"SCI_WORDPARTRIGHTEXTEND"}, //2393
{SCI_SETVISIBLEPOLICY,"SCI_SETVISIBLEPOLICY"}, //2394
{SCI_DELLINELEFT,"SCI_DELLINELEFT"}, //2395
{SCI_DELLINERIGHT,"SCI_DELLINERIGHT"}, //2396
{SCI_SETXOFFSET,"SCI_SETXOFFSET"}, //2397
{SCI_GETXOFFSET,"SCI_GETXOFFSET"}, //2398
{SCI_CHOOSECARETX,"SCI_CHOOSECARETX"}, //2399
{SCI_GRABFOCUS,"SCI_GRABFOCUS"}, //2400
{SCI_SETXCARETPOLICY,"SCI_SETXCARETPOLICY"}, //2402
{SCI_SETYCARETPOLICY,"SCI_SETYCARETPOLICY"}, //2403
{SCI_SETPRINTWRAPMODE,"SCI_SETPRINTWRAPMODE"}, //2406
{SCI_GETPRINTWRAPMODE,"SCI_GETPRINTWRAPMODE"}, //2407
{SCI_SETHOTSPOTACTIVEFORE,"SCI_SETHOTSPOTACTIVEFORE"}, //2410
{SCI_GETHOTSPOTACTIVEFORE,"SCI_GETHOTSPOTACTIVEFORE"}, //2494
{SCI_SETHOTSPOTACTIVEBACK,"SCI_SETHOTSPOTACTIVEBACK"}, //2411
{SCI_GETHOTSPOTACTIVEBACK,"SCI_GETHOTSPOTACTIVEBACK"}, //2495
{SCI_SETHOTSPOTACTIVEUNDERLINE,"SCI_SETHOTSPOTACTIVEUNDERLINE"}, //2412
{SCI_GETHOTSPOTACTIVEUNDERLINE,"SCI_GETHOTSPOTACTIVEUNDERLINE"}, //2496
{SCI_SETHOTSPOTSINGLELINE,"SCI_SETHOTSPOTSINGLELINE"}, //2421
{SCI_GETHOTSPOTSINGLELINE,"SCI_GETHOTSPOTSINGLELINE"}, //2497
{SCI_PARADOWN,"SCI_PARADOWN"}, //2413
{SCI_PARADOWNEXTEND,"SCI_PARADOWNEXTEND"}, //2414
{SCI_PARAUP,"SCI_PARAUP"}, //2415
{SCI_PARAUPEXTEND,"SCI_PARAUPEXTEND"}, //2416
{SCI_POSITIONBEFORE,"SCI_POSITIONBEFORE"}, //2417
{SCI_POSITIONAFTER,"SCI_POSITIONAFTER"}, //2418
{SCI_COPYRANGE,"SCI_COPYRANGE"}, //2419
{SCI_COPYTEXT,"SCI_COPYTEXT"}, //2420
{SCI_SETSELECTIONMODE,"SCI_SETSELECTIONMODE"}, //2422
{SCI_GETSELECTIONMODE,"SCI_GETSELECTIONMODE"}, //2423
{SCI_GETLINESELSTARTPOSITION,"SCI_GETLINESELSTARTPOSITION"}, //2424
{SCI_GETLINESELENDPOSITION,"SCI_GETLINESELENDPOSITION"}, //2425
{SCI_LINEDOWNRECTEXTEND,"SCI_LINEDOWNRECTEXTEND"}, //2426
{SCI_LINEUPRECTEXTEND,"SCI_LINEUPRECTEXTEND"}, //2427
{SCI_CHARLEFTRECTEXTEND,"SCI_CHARLEFTRECTEXTEND"}, //2428
{SCI_CHARRIGHTRECTEXTEND,"SCI_CHARRIGHTRECTEXTEND"}, //2429
{SCI_HOMERECTEXTEND,"SCI_HOMERECTEXTEND"}, //2430
{SCI_VCHOMERECTEXTEND,"SCI_VCHOMERECTEXTEND"}, //2431
{SCI_LINEENDRECTEXTEND,"SCI_LINEENDRECTEXTEND"}, //2432
{SCI_PAGEUPRECTEXTEND,"SCI_PAGEUPRECTEXTEND"}, //2433
{SCI_PAGEDOWNRECTEXTEND,"SCI_PAGEDOWNRECTEXTEND"}, //2434
{SCI_STUTTEREDPAGEUP,"SCI_STUTTEREDPAGEUP"}, //2435
{SCI_STUTTEREDPAGEUPEXTEND,"SCI_STUTTEREDPAGEUPEXTEND"}, //2436
{SCI_STUTTEREDPAGEDOWN,"SCI_STUTTEREDPAGEDOWN"}, //2437
{SCI_STUTTEREDPAGEDOWNEXTEND,"SCI_STUTTEREDPAGEDOWNEXTEND"}, //2438
{SCI_WORDLEFTEND,"SCI_WORDLEFTEND"}, //2439
{SCI_WORDLEFTENDEXTEND,"SCI_WORDLEFTENDEXTEND"}, //2440
{SCI_WORDRIGHTEND,"SCI_WORDRIGHTEND"}, //2441
{SCI_WORDRIGHTENDEXTEND,"SCI_WORDRIGHTENDEXTEND"}, //2442
{SCI_SETWHITESPACECHARS,"SCI_SETWHITESPACECHARS"}, //2443
{SCI_SETCHARSDEFAULT,"SCI_SETCHARSDEFAULT"}, //2444
{SCI_AUTOCGETCURRENT,"SCI_AUTOCGETCURRENT"}, //2445
{SCI_AUTOCGETCURRENTTEXT,"SCI_AUTOCGETCURRENTTEXT"}, //2610
{SCI_ALLOCATE,"SCI_ALLOCATE"}, //2446
{SCI_TARGETASUTF8,"SCI_TARGETASUTF8"}, //2447
{SCI_SETLENGTHFORENCODE,"SCI_SETLENGTHFORENCODE"}, //2448
{SCI_ENCODEDFROMUTF8,"SCI_ENCODEDFROMUTF8"}, //2449
{SCI_FINDCOLUMN,"SCI_FINDCOLUMN"}, //2456
{SCI_GETCARETSTICKY,"SCI_GETCARETSTICKY"}, //2457
{SCI_SETCARETSTICKY,"SCI_SETCARETSTICKY"}, //2458
{SCI_TOGGLECARETSTICKY,"SCI_TOGGLECARETSTICKY"}, //2459
{SCI_SETPASTECONVERTENDINGS,"SCI_SETPASTECONVERTENDINGS"}, //2467
{SCI_GETPASTECONVERTENDINGS,"SCI_GETPASTECONVERTENDINGS"}, //2468
{SCI_SELECTIONDUPLICATE,"SCI_SELECTIONDUPLICATE"}, //2469
{SCI_SETCARETLINEBACKALPHA,"SCI_SETCARETLINEBACKALPHA"}, //2470
{SCI_GETCARETLINEBACKALPHA,"SCI_GETCARETLINEBACKALPHA"}, //2471
{SCI_SETCARETSTYLE,"SCI_SETCARETSTYLE"}, //2512
{SCI_GETCARETSTYLE,"SCI_GETCARETSTYLE"}, //2513
{SCI_SETINDICATORCURRENT,"SCI_SETINDICATORCURRENT"}, //2500
{SCI_GETINDICATORCURRENT,"SCI_GETINDICATORCURRENT"}, //2501
{SCI_SETINDICATORVALUE,"SCI_SETINDICATORVALUE"}, //2502
{SCI_GETINDICATORVALUE,"SCI_GETINDICATORVALUE"}, //2503
{SCI_INDICATORFILLRANGE,"SCI_INDICATORFILLRANGE"}, //2504
{SCI_INDICATORCLEARRANGE,"SCI_INDICATORCLEARRANGE"}, //2505
{SCI_INDICATORALLONFOR,"SCI_INDICATORALLONFOR"}, //2506
{SCI_INDICATORVALUEAT,"SCI_INDICATORVALUEAT"}, //2507
{SCI_INDICATORSTART,"SCI_INDICATORSTART"}, //2508
{SCI_INDICATOREND,"SCI_INDICATOREND"}, //2509
{SCI_SETPOSITIONCACHE,"SCI_SETPOSITIONCACHE"}, //2514
{SCI_GETPOSITIONCACHE,"SCI_GETPOSITIONCACHE"}, //2515
{SCI_COPYALLOWLINE,"SCI_COPYALLOWLINE"}, //2519
{SCI_GETCHARACTERPOINTER,"SCI_GETCHARACTERPOINTER"}, //2520
{SCI_SETKEYSUNICODE,"SCI_SETKEYSUNICODE"}, //2521
{SCI_GETKEYSUNICODE,"SCI_GETKEYSUNICODE"}, //2522
{SCI_INDICSETALPHA,"SCI_INDICSETALPHA"}, //2523
{SCI_INDICGETALPHA,"SCI_INDICGETALPHA"}, //2524
{SCI_INDICSETOUTLINEALPHA,"SCI_INDICSETOUTLINEALPHA"}, //2558
{SCI_INDICGETOUTLINEALPHA,"SCI_INDICGETOUTLINEALPHA"}, //2559
{SCI_SETEXTRAASCENT,"SCI_SETEXTRAASCENT"}, //2525
{SCI_GETEXTRAASCENT,"SCI_GETEXTRAASCENT"}, //2526
{SCI_SETEXTRADESCENT,"SCI_SETEXTRADESCENT"}, //2527
{SCI_GETEXTRADESCENT,"SCI_GETEXTRADESCENT"}, //2528
{SCI_MARKERSYMBOLDEFINED,"SCI_MARKERSYMBOLDEFINED"}, //2529
{SCI_MARGINSETTEXT,"SCI_MARGINSETTEXT"}, //2530
{SCI_MARGINGETTEXT,"SCI_MARGINGETTEXT"}, //2531
{SCI_MARGINSETSTYLE,"SCI_MARGINSETSTYLE"}, //2532
{SCI_MARGINGETSTYLE,"SCI_MARGINGETSTYLE"}, //2533
{SCI_MARGINSETSTYLES,"SCI_MARGINSETSTYLES"}, //2534
{SCI_MARGINGETSTYLES,"SCI_MARGINGETSTYLES"}, //2535
{SCI_MARGINTEXTCLEARALL,"SCI_MARGINTEXTCLEARALL"}, //2536
{SCI_MARGINSETSTYLEOFFSET,"SCI_MARGINSETSTYLEOFFSET"}, //2537
{SCI_MARGINGETSTYLEOFFSET,"SCI_MARGINGETSTYLEOFFSET"}, //2538
{SCI_SETMARGINOPTIONS,"SCI_SETMARGINOPTIONS"}, //2539
{SCI_GETMARGINOPTIONS,"SCI_GETMARGINOPTIONS"}, //2557
{SCI_ANNOTATIONSETTEXT,"SCI_ANNOTATIONSETTEXT"}, //2540
{SCI_ANNOTATIONGETTEXT,"SCI_ANNOTATIONGETTEXT"}, //2541
{SCI_ANNOTATIONSETSTYLE,"SCI_ANNOTATIONSETSTYLE"}, //2542
{SCI_ANNOTATIONGETSTYLE,"SCI_ANNOTATIONGETSTYLE"}, //2543
{SCI_ANNOTATIONSETSTYLES,"SCI_ANNOTATIONSETSTYLES"}, //2544
{SCI_ANNOTATIONGETSTYLES,"SCI_ANNOTATIONGETSTYLES"}, //2545
{SCI_ANNOTATIONGETLINES,"SCI_ANNOTATIONGETLINES"}, //2546
{SCI_ANNOTATIONCLEARALL,"SCI_ANNOTATIONCLEARALL"}, //2547
{SCI_ANNOTATIONSETVISIBLE,"SCI_ANNOTATIONSETVISIBLE"}, //2548
{SCI_ANNOTATIONGETVISIBLE,"SCI_ANNOTATIONGETVISIBLE"}, //2549
{SCI_ANNOTATIONSETSTYLEOFFSET,"SCI_ANNOTATIONSETSTYLEOFFSET"}, //2550
{SCI_ANNOTATIONGETSTYLEOFFSET,"SCI_ANNOTATIONGETSTYLEOFFSET"}, //2551
{SCI_ADDUNDOACTION,"SCI_ADDUNDOACTION"}, //2560
{SCI_CHARPOSITIONFROMPOINT,"SCI_CHARPOSITIONFROMPOINT"}, //2561
{SCI_CHARPOSITIONFROMPOINTCLOSE,"SCI_CHARPOSITIONFROMPOINTCLOSE"}, //2562
{SCI_SETMULTIPLESELECTION,"SCI_SETMULTIPLESELECTION"}, //2563
{SCI_GETMULTIPLESELECTION,"SCI_GETMULTIPLESELECTION"}, //2564
{SCI_SETADDITIONALSELECTIONTYPING,"SCI_SETADDITIONALSELECTIONTYPING"}, //2565
{SCI_GETADDITIONALSELECTIONTYPING,"SCI_GETADDITIONALSELECTIONTYPING"}, //2566
{SCI_SETADDITIONALCARETSBLINK,"SCI_SETADDITIONALCARETSBLINK"}, //2567
{SCI_GETADDITIONALCARETSBLINK,"SCI_GETADDITIONALCARETSBLINK"}, //2568
{SCI_SETADDITIONALCARETSVISIBLE,"SCI_SETADDITIONALCARETSVISIBLE"}, //2608
{SCI_GETADDITIONALCARETSVISIBLE,"SCI_GETADDITIONALCARETSVISIBLE"}, //2609
{SCI_GETSELECTIONS,"SCI_GETSELECTIONS"}, //2570
{SCI_CLEARSELECTIONS,"SCI_CLEARSELECTIONS"}, //2571
{SCI_SETSELECTION,"SCI_SETSELECTION"}, //2572
{SCI_ADDSELECTION,"SCI_ADDSELECTION"}, //2573
{SCI_SETMAINSELECTION,"SCI_SETMAINSELECTION"}, //2574
{SCI_GETMAINSELECTION,"SCI_GETMAINSELECTION"}, //2575
{SCI_SETSELECTIONNCARET,"SCI_SETSELECTIONNCARET"}, //2576
{SCI_GETSELECTIONNCARET,"SCI_GETSELECTIONNCARET"}, //2577
{SCI_SETSELECTIONNANCHOR,"SCI_SETSELECTIONNANCHOR"}, //2578
{SCI_GETSELECTIONNANCHOR,"SCI_GETSELECTIONNANCHOR"}, //2579
{SCI_SETSELECTIONNCARETVIRTUALSPACE,"SCI_SETSELECTIONNCARETVIRTUALSPACE"}, //2580
{SCI_GETSELECTIONNCARETVIRTUALSPACE,"SCI_GETSELECTIONNCARETVIRTUALSPACE"}, //2581
{SCI_SETSELECTIONNANCHORVIRTUALSPACE,"SCI_SETSELECTIONNANCHORVIRTUALSPACE"}, //2582
{SCI_GETSELECTIONNANCHORVIRTUALSPACE,"SCI_GETSELECTIONNANCHORVIRTUALSPACE"}, //2583
{SCI_SETSELECTIONNSTART,"SCI_SETSELECTIONNSTART"}, //2584
{SCI_GETSELECTIONNSTART,"SCI_GETSELECTIONNSTART"}, //2585
{SCI_SETSELECTIONNEND,"SCI_SETSELECTIONNEND"}, //2586
{SCI_GETSELECTIONNEND,"SCI_GETSELECTIONNEND"}, //2587
{SCI_SETRECTANGULARSELECTIONCARET,"SCI_SETRECTANGULARSELECTIONCARET"}, //2588
{SCI_GETRECTANGULARSELECTIONCARET,"SCI_GETRECTANGULARSELECTIONCARET"}, //2589
{SCI_SETRECTANGULARSELECTIONANCHOR,"SCI_SETRECTANGULARSELECTIONANCHOR"}, //2590
{SCI_GETRECTANGULARSELECTIONANCHOR,"SCI_GETRECTANGULARSELECTIONANCHOR"}, //2591
{SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE,"SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE"}, //2592
{SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE,"SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE"}, //2593
{SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE,"SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE"}, //2594
{SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE,"SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE"}, //2595
{SCI_SETVIRTUALSPACEOPTIONS,"SCI_SETVIRTUALSPACEOPTIONS"}, //2596
{SCI_GETVIRTUALSPACEOPTIONS,"SCI_GETVIRTUALSPACEOPTIONS"}, //2597
{SCI_SETRECTANGULARSELECTIONMODIFIER,"SCI_SETRECTANGULARSELECTIONMODIFIER"}, //2598
{SCI_GETRECTANGULARSELECTIONMODIFIER,"SCI_GETRECTANGULARSELECTIONMODIFIER"}, //2599
{SCI_SETADDITIONALSELFORE,"SCI_SETADDITIONALSELFORE"}, //2600
{SCI_SETADDITIONALSELBACK,"SCI_SETADDITIONALSELBACK"}, //2601
{SCI_SETADDITIONALSELALPHA,"SCI_SETADDITIONALSELALPHA"}, //2602
{SCI_GETADDITIONALSELALPHA,"SCI_GETADDITIONALSELALPHA"}, //2603
{SCI_SETADDITIONALCARETFORE,"SCI_SETADDITIONALCARETFORE"}, //2604
{SCI_GETADDITIONALCARETFORE,"SCI_GETADDITIONALCARETFORE"}, //2605
{SCI_ROTATESELECTION,"SCI_ROTATESELECTION"}, //2606
{SCI_SWAPMAINANCHORCARET,"SCI_SWAPMAINANCHORCARET"}, //2607
{SCI_CHANGELEXERSTATE,"SCI_CHANGELEXERSTATE"}, //2617
{SCI_CONTRACTEDFOLDNEXT,"SCI_CONTRACTEDFOLDNEXT"}, //2618
{SCI_VERTICALCENTRECARET,"SCI_VERTICALCENTRECARET"}, //2619
{SCI_MOVESELECTEDLINESUP,"SCI_MOVESELECTEDLINESUP"}, //2620
{SCI_MOVESELECTEDLINESDOWN,"SCI_MOVESELECTEDLINESDOWN"}, //2621
{SCI_SETIDENTIFIER,"SCI_SETIDENTIFIER"}, //2622
{SCI_GETIDENTIFIER,"SCI_GETIDENTIFIER"}, //2623
{SCI_STARTRECORD,"SCI_STARTRECORD"}, //3001
{SCI_STOPRECORD,"SCI_STOPRECORD"}, //3002
{SCI_SETLEXER,"SCI_SETLEXER"}, //4001
{SCI_GETLEXER,"SCI_GETLEXER"}, //4002
{SCI_COLOURISE,"SCI_COLOURISE"}, //4003
{SCI_SETPROPERTY,"SCI_SETPROPERTY"}, //4004
{SCI_SETKEYWORDS,"SCI_SETKEYWORDS"}, //4005
{SCI_SETLEXERLANGUAGE,"SCI_SETLEXERLANGUAGE"}, //4006
{SCI_LOADLEXERLIBRARY,"SCI_LOADLEXERLIBRARY"}, //4007
{SCI_GETPROPERTY,"SCI_GETPROPERTY"}, //4008
{SCI_GETPROPERTYEXPANDED,"SCI_GETPROPERTYEXPANDED"}, //4009
{SCI_GETPROPERTYINT,"SCI_GETPROPERTYINT"}, //4010
{SCI_GETSTYLEBITSNEEDED,"SCI_GETSTYLEBITSNEEDED"}, //4011
{SCI_GETLEXERLANGUAGE,"SCI_GETLEXERLANGUAGE"}, //4012
{SCI_PRIVATELEXERCALL,"SCI_PRIVATELEXERCALL"}, //4013
{SCI_PROPERTYNAMES,"SCI_PROPERTYNAMES"}, //4014
{SCI_PROPERTYTYPE,"SCI_PROPERTYTYPE"}, //4015
{SCI_DESCRIBEPROPERTY,"SCI_DESCRIBEPROPERTY"}, //4016
{SCI_DESCRIBEKEYWORDSETS,"SCI_DESCRIBEKEYWORDSETS"}, //4017
};

char *virtual_keys[256]={
"key0", //0
"LBUTTON", //1
"RBUTTON", //2
"CANCEL", //3
"MBUTTON", //4
"key5", //5
"key6", //6
"key7", //7
"BACK", //8
"TAB", //9
"key10", //10
"key11", //11
"CLEAR", //12
"RETURN", //13
"key14", //14
"key15", //15
"SHIFT", //16
"CONTROL", //17
"MENU", //18
"PAUSE", //19
"CAPITAL", //20
"HANGEUL", //21
"key22", //22
"JUNJA", //23
"FINAL", //24
"HANJA", //25
"key26", //26
"ESCAPE", //27
"CONVERT", //28
"NONCONVERT", //29
"ACCEPT", //30
"MODECHANGE", //31
"SPACE", //32
"PRIOR", //33
"NEXT", //34
"END", //35
"HOME", //36
"LEFT", //37
"UP", //38
"RIGHT", //39
"DOWN", //40
"SELECT", //41
"PRINT", //42
"EXECUTE", //43
"SNAPSHOT", //44
"INSERT", //45
"DELETE", //46
"HELP", //47
"0", //48
"1", //49
"2", //50
"3", //51
"4", //52
"5", //53
"6", //54
"7", //55
"8", //56
"9", //57
"key58", //58
"key59", //59
"key60", //60
"key61", //61
"key62", //62
"key63", //63
"key64", //64
"A", //65
"B", //66
"C", //67
"D", //68
"E", //69
"F", //70
"G", //71
"H", //72
"I", //73
"J", //74
"K", //75
"L", //76
"M", //77
"N", //78
"O", //79
"P", //80
"Q", //81
"R", //82
"S", //83
"T", //84
"U", //85
"V", //86
"W", //87
"X", //88
"Y", //89
"Z", //90
"LWIN", //91
"RWIN", //92
"APPS", //93
"key94", //94
"key95", //95
"NUMPAD0", //96
"NUMPAD1", //97
"NUMPAD2", //98
"NUMPAD3", //99
"NUMPAD4", //100
"NUMPAD5", //101
"NUMPAD6", //102
"NUMPAD7", //103
"NUMPAD8", //104
"NUMPAD9", //105
"MULTIPLY", //106
"ADD", //107
"SEPARATOR", //108
"SUBTRACT", //109
"DECIMAL", //110
"DIVIDE", //111
"F1", //112
"F2", //113
"F3", //114
"F4", //115
"F5", //116
"F6", //117
"F7", //118
"F8", //119
"F9", //120
"F10", //121
"F11", //122
"F12", //123
"F13", //124
"F14", //125
"F15", //126
"F16", //127
"F17", //128
"F18", //129
"F19", //130
"F20", //131
"F21", //132
"F22", //133
"F23", //134
"F24", //135
"key136", //136
"key137", //137
"key138", //138
"key139", //139
"key140", //140
"key141", //141
"key142", //142
"key143", //143
"NUMLOCK", //144
"SCROLL", //145
"key146", //146
"key147", //147
"key148", //148
"key149", //149
"key150", //150
"key151", //151
"key152", //152
"key153", //153
"key154", //154
"key155", //155
"key156", //156
"key157", //157
"key158", //158
"key159", //159
"LSHIFT", //160
"RSHIFT", //161
"LCONTROL", //162
"RCONTROL", //163
"LMENU", //164
"RMENU", //165
"key166", //166
"key167", //167
"key168", //168
"key169", //169
"key170", //170
"key171", //171
"key172", //172
"key173", //173
"key174", //174
"key175", //175
"key176", //176
"key177", //177
"key178", //178
"key179", //179
"key180", //180
"key181", //181
"key182", //182
"key183", //183
"key184", //184
"key185", //185
"key186", //186
"key187", //187
"key188", //188
"key189", //189
"key190", //190
"key191", //191
"key192", //192
"key193", //193
"key194", //194
"key195", //195
"key196", //196
"key197", //197
"key198", //198
"key199", //199
"key200", //200
"key201", //201
"key202", //202
"key203", //203
"key204", //204
"key205", //205
"key206", //206
"key207", //207
"key208", //208
"key209", //209
"key210", //210
"key211", //211
"key212", //212
"key213", //213
"key214", //214
"key215", //215
"key216", //216
"key217", //217
"key218", //218
"key219", //219
"key220", //220
"key221", //221
"key222", //222
"key223", //223
"key224", //224
"key225", //225
"key226", //226
"key227", //227
"key228", //228
"PROCESSKEY", //229
"key230", //230
"key231", //231
"key232", //232
"key233", //233
"key234", //234
"key235", //235
"key236", //236
"key237", //237
"key238", //238
"key239", //239
"key240", //240
"key241", //241
"key242", //242
"key243", //243
"key244", //244
"key245", //245
"ATTN", //246
"CRSEL", //247
"EXSEL", //248
"EREOF", //249
"PLAY", //250
"ZOOM", //251
"NONAME", //252
"PA1", //253
"OEM_CLEAR", //254
"key255", //255
};
HWND ghconsole=0;
int move_console(int x,int y,int w,int h)
{
	if(ghconsole!=0)
		SetWindowPos(ghconsole,0,x,y,w,h,SWP_NOZORDER);
	return 0;
}
#define _O_TEXT         0x4000  /* file mode is text (translated) */
void open_console()
{
	HWND hcon;
	FILE *hf;
	static BYTE consolecreated=FALSE;
	static int hcrt=0;
	static HWND (*GetConsoleWindow)(void)=0;

	if(consolecreated==TRUE)
	{
		if(ghconsole!=0)
			ShowWindow(ghconsole,SW_SHOW);
		hcon=(HWND)GetStdHandle(STD_INPUT_HANDLE);
		FlushConsoleInputBuffer(hcon);
		return;
	}
	AllocConsole();
	hcrt=_open_osfhandle((long)GetStdHandle(STD_OUTPUT_HANDLE),_O_TEXT);

	fflush(stdin);
	hf=_fdopen(hcrt,"w");
	*stdout=*hf;
	setvbuf(stdout,NULL,_IONBF,0);
	consolecreated=TRUE;
	if(GetConsoleWindow==0){
		HMODULE hmod=LoadLibrary("kernel32.dll");
		if(hmod!=0){
			GetConsoleWindow=(HWND)GetProcAddress(hmod,"GetConsoleWindow");
			if(GetConsoleWindow!=0){
				ghconsole=GetConsoleWindow();
			}
		}
	}

}
void hide_console()
{
	if(ghconsole!=0){
		ShowWindow(ghconsole,SW_HIDE);
		SetForegroundWindow(ghconsole);
	}
}
void print_key(int key)
{
	if(key>(sizeof(virtual_keys)/sizeof(char *)))
		printf("key=%i\n",key);
	else
		printf("key=%s (%i) (%02X)\n",virtual_keys[key],key,key);
}

int get_key_str(int key,char *str)
{
	if(key>(sizeof(virtual_keys)/sizeof(char *)))
		sprintf(str,"key=%i",key);
	else
		sprintf(str,"%s",virtual_keys[key]);
	return TRUE;
}
int print_capture(BYTE *keys,char *str,int len)
{
	int i,count=0,max=4;
	str[0]=0;
	for(i=0;i<256;i++){
		if(keys[i]!=0){
			if(count!=0)
				strcat(str,"+");
			_snprintf(str+strlen(str),len-strlen(str),"%s",virtual_keys[i]);
			count++;
			if(count>=max)
				break;
		}
	}
	return TRUE;
}
void print_msg(int msg,int wparam,int lparam)
{
	int i;
	static int create_console=FALSE;
	static DWORD tick=0;
	DWORD time;
	if(create_console==FALSE){
		open_console();
		move_console(1927,0,2845-1927,1170);
		create_console=TRUE;
	}
	time=GetTickCount();
	if((time-tick)>250)
		printf("---\n");
	tick=time;
	for(i=0;i<sizeof(wm_names)/sizeof(NAME);i++){
		if(wm_names[i].val==msg){
			printf("%-20s lparam=%08X wparam=%08X x=%3i y=%3i\n",wm_names[i].name,lparam,wparam,LOWORD(lparam),HIWORD(lparam));
			return;
		}
	}
	printf("msg=%08X wparam=%08X lparam=%08X x=%3i y=%3i %08X\n",msg,wparam,lparam,LOWORD(lparam),HIWORD(lparam),time);
}


char *strstri(char *src,char *sub)
{
	int index=0,sub_index=0;
	char a;
	char *start=0;
	while((a=src[index])!=0){
		char b;
		a=tolower(a);
		b=sub[sub_index];
		if(0==sub_index)
			start=src+index;
		b=tolower(b);
		if(0==b)
			return start;
		if(a==b){
			sub_index++;
		}else{
			sub_index=0;
		}
		index++;
	}
	if(sub_index>0){
		if(0==sub[sub_index])
			return start;
	}
	return 0;
}
void show_tick()
{
	static DWORD tick=0;
	DWORD time;
	time=GetTickCount();
	if((time-tick)>250)
		printf("---\n");
	tick=time;
}
void print_sci_msg(int msg,int wparam,int lparam)
{
	int i;
	static int create_console=FALSE;
	if(create_console==FALSE){
		open_console();
		move_console(1927,0,2845-1927,1170);
		create_console=TRUE;
	}
	for(i=0;i<sizeof(sci_names)/sizeof(NAME);i++){
		if(sci_names[i].val==msg){
			char *n=sci_names[i].name;
			if(1||strstri(n,"mode")){//||strstri(n,"lex")){
				show_tick();
				if(strstri(n,"SETSTYLING"))
					printf("XXXX\n");
				printf("%-20s wparam=%08X lparam=%08X x=%3i y=%3i\n",sci_names[i].name,wparam,lparam,LOWORD(lparam),HIWORD(lparam));
				return;
			}else{
				break;
			}
		}
	}
}

int save_input(BYTE *keys,int inp)
{
	if(inp>=256)
		return 0;
	keys[inp]=1;
	return TRUE;
}
int sanatize_string(char *str,int len)
{
	int i;
	for(i=0;i<len;i++){
		if((str[i]>='0' && str[i]<='9') || (str[i]>='A' && str[i]<='Z') || (str[i]>='a' && str[i]<='z'))
			;
		else
			str[i]=' ';
	}
	return TRUE;
}
int print_last_error()
{
	char *msg=0;
	FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM,
		NULL,
		GetLastError(),
		MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
		(LPTSTR) &msg,
		0,
		NULL 
		);
	printf("%s\n",msg);
	LocalFree(msg);
	return TRUE;

}
#endif // __DEBUG_PRINT_H